### ISSUE TITLE
[Question] Any example ?

### ISSUE THREAD

**Issue by rianonehub** [witcher112/electron-app-universal-protocol-client#2]
Hi,

Is there any example (real project), to use this module ?
Because I little bit confused about where to place the initialized code using **await** in electron main process script (top-level).

Thanks

**Comment by witcher112** [comment]
Example added :)

https://github.com/witcher112/electron-app-universal-protocol-client/blob/main/example/main.js

**Comment by rianonehub** [comment]
@witcher112 thanks, appreciated 😃
