### ISSUE TITLE
No native build was found for platform darwin

### ISSUE THREAD

**Issue by eden-lane** [witcher112/electron-app-universal-protocol-client#3]
I'm getting this error when I require the module:
```
Error: No native build was found for 
platform=darwin 
arch=arm64 
runtime=electron 
abi=119 
uv=1 
armv=8 
libc=glibc 
node=18.18.2 
electron=28.1.0 
webpack=true
```

Is there any solution to this?

I've tried to add lib to extrernals of webpack, but it didn't help:

```js
 externals: {
    keytar: "require('keytar')",
    electronAppUniversalProtocolClient: "require('electron-app-universal-protocol-client').default",
  },
```

**Comment by elliotmoose** [comment]
+1, am facing this at the moment

**Comment by jason-dark** [comment]
+1 same issue here

**Comment by juxnpxblo** [comment]
I was able to solve it on my project by adding **externals: ["electron-app-universal-protocol-client"]** to my main script webpack config

the error was **No native build was found for platform=linux arch=x64 runtime=electron abi=114 uv=1 libc=glibc node=18.14.0 electron=24.1.1 webpack=true**

**Comment by witcher112** [comment]
Hi,

The issue has been resolved in 2.x.x: https://github.com/witcher112/electron-app-universal-protocol-client/releases/tag/v2.0.0 (although 2.0.1 is the first 2.x.x version due to CI failure)

Thanks for using the package :D!

Best regards,
Tomasz
