### ISSUE TITLE
Build failure (Darwin, M2)

### ISSUE THREAD

**Issue by karlanke** [witcher112/electron-app-universal-protocol-client#4]
I'm getting this when trying to run in dev mode:
```
 CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  LIBTOOL-STATIC Release/nothing.a
  warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  SOLINK_MODULE(target) Release/electron-app-universal-protocol-client.node
  clang: error: no such file or directory: 'Release/obj.target/electron-app-universal-protocol-client/src/lib-macos.o'
  make: *** [Release/electron-app-universal-protocol-client.node] Error 1
  Error: `make` failed with exit code: 2
  at ChildProcess.onExit (/<app_folder>/node_modules/node-gyp/lib/build.js:203:23)
  at ChildProcess.emit (node:events:518:28)
  at ChildProcess._handle.onexit (node:internal/child_process:294:12)

An unhandled rejection has occurred inside Forge:
Error: node-gyp failed to rebuild '/<app_folder>/node_modules/electron-app-universal-protocol-client'
at ChildProcess.<anonymous> (/<app_folder>/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

```

**Comment by nova3uk** [comment]
Noticed the same, because they dev included the binding.gyp in the package, but not the sourcecode, so it fails. If you delete the binding.gyp it gets rid of the compile time error. but you of course then depend on the code working without access to sourcecode.

**Comment by obetame** [comment]
I encountered the same problem. There was no problem with the first installation. When I upgraded electron-builder and rebuilt, an error occurred. So I deleted electron-app-universal-protocol-client, and then rebuilt successfully. After installing electron-app-universal-protocol-client again, I found that there was no such problem.

**Comment by witcher112** [comment]
Hi,

The issue has been resolved in 2.x.x: https://github.com/witcher112/electron-app-universal-protocol-client/releases/tag/v2.0.0 (although 2.0.1 is the first 2.x.x version due to CI failure)

Thanks for using the package :D!

Best regards,
Tomasz
