### ISSUE TITLE
No prebuilt binaries available for arm64 windows

### ISSUE THREAD

**Issue by jkarthic** [witcher112/electron-app-universal-protocol-client#6]
Windows release has published only x64 binaries. 
I am not able to install and run this package on arm64 windows binaries and the corresponding binaries are missing. I am getting the following error for this package on arm64 windows.
```
[10:34:35 am] [ERROR] Error: No native build was found for platform=win32 arch=arm64 runtime=electron abi=125 uv=1 armv=8 libc=glibc node=20.16.0 electron=31.4.0
    loaded from: C:\karthick\highlight\node_modules\.pnpm\electron-app-universal-protocol-client@1.3.0_electron@31.4.0\node_modules\electron-app-universal-protocol-client
```

Is it possible to publish a release with binaries for arm64 windows?

**Comment by witcher112** [comment]
Hi,

The issue has been resolved in 2.x.x: https://github.com/witcher112/electron-app-universal-protocol-client/releases/tag/v2.0.0 (although 2.0.1 is the first 2.x.x version due to CI failure)

Thanks for using the package :D!

Best regards,
Tomasz

**Comment by jkarthic** [comment]
Thank you very much!
